### ISSUE TITLE
Error "Cannot read property 'model' of undefined"

### ISSUE THREAD

**Issue by fakhamatia** [fabiospampinato/vscode-search-open-all-results#2]
Some times in VSCode show this error.
"Cannot read property 'model' of undefined"

![Screenshot from 2019-04-18 23-44-12](https://user-images.githubusercontent.com/20030910/56385330-0698a800-6234-11e9-9e1e-8e1decceb4b1.png)

**Comment by richard-scott** [comment]
@fakhamatia This one seems to work: [Open Matching Files](https://marketplace.visualstudio.com/items?itemName=bcanzanella.openmatchingfiles).

**Comment by fabiospampinato** [comment]
Any ideas on how to reproduce this? Did you notice any patterns?

**Comment by fabiospampinato** [comment]
Closing for lack of info on how to reproduce this. Also the extension got rewritten, maybe v2 doesn't have this problem anymore?

If anybody can still reproduce the problem please tell me, hopefully also with some way on how to reproduce this.
